### ISSUE TITLE
请问能修改特效，特效是视频文件格式还是？

### ISSUE THREAD

**Issue by jihan513** [SimonCherryGZ/ARCamera#11]

**Comment by SimonCherryGZ** [comment]
是用GLSL写的。
要实现自己的特效，除了可以参考README.md提到的几个项目外，还可以看看这个项目：
https://github.com/nekocode/CameraFilter
它每个滤镜特效的缩略图旁边都附有ShaderToy网站的链接，可以浏览其GLSL代码和实时效果。

**Comment by jihan513** [comment]
好 谢谢你
