### ISSUE TITLE
人脸交换关键点文本不存在

### ISSUE THREAD

**Issue by fenggit** [SimonCherryGZ/ARCamera#19]
为什么一直是关键点文本不存在

**Comment by SimonCherryGZ** [comment]
很抱歉隔了这么久才回复。
SwapFaceActivity只是我测试用的，
所需的人脸关键点txt是我事先生成好后，复制到那个目录里面的，
所以你这边就一直报找不到了。
除了ARCamActivity，其他页面都只是测试用的，很抱歉注释中没有说明。
