### ISSUE TITLE
人脸晃动时贴图跟不上，另外手机晃动时贴图移动的坐标不对的

### ISSUE THREAD

**Issue by WangShuo1143368701** [SimonCherryGZ/ARCamera#4]

**Comment by SimonCherryGZ** [comment]
人脸检测不是我做的，是用别人的SDK做的，所以这个问题我也没办法优化。
或者你参考下能不能用其他开源的人脸检测库来实现：
https://github.com/tzutalin/dlib-android
https://github.com/RoboPai/sdm
