### ISSUE TITLE
有一个问题。。

### ISSUE THREAD

**Issue by YuJunKui1995** [SimonCherryGZ/ARCamera#5]
人脸识别是商汤的，而商汤一年授权费高达百万

**Comment by SimonCherryGZ** [comment]
呃，我是从[https://github.com/Martin20150405/Omoshiroi](https://github.com/Martin20150405/Omoshiroi)找到的，
没有商业用途的打算，就没有去了解授权问题了。


如果你想找免费的，可以看下这个，我之前也尝试过使用开源的人脸识别库来实现：
[https://github.com/SimonCherryGZ/face-landmark-android](https://github.com/SimonCherryGZ/face-landmark-android)
此项目用的人脸识别库是[dlib-android](https://github.com/tzutalin/dlib-android)，能识别68个关键点。
需要自己根据关键点做三维姿态估算，来得到旋转和位移的数值，还有嘴巴开合等。
Dlib需要依赖一个约100M的数据，[这个issue](https://github.com/tzutalin/dlib-android-app/issues/20)提到了如何减少这个数据文件的体积，不过我没有试过。
另外[这篇文章](https://www.learnopencv.com/speeding-up-dlib-facial-landmark-detector/)提到了如何加快Dlib的识别速度，我都尝试过了，但是效果还是不太理想。

前段时间找到这个开源项目：[https://github.com/RoboPai/sdm](https://github.com/RoboPai/sdm)
看起来不错，不过还没时间去试。
