### ISSUE TITLE
贴纸问题

### ISSUE THREAD

**Issue by lin65505578** [SimonCherryGZ/ARCamera#6]
hi，请教个问题。
2D或3D贴纸，用opengl 实现的还是直接调用商业的sdk

**Comment by SimonCherryGZ** [comment]
贴纸的位置、移动需要人脸关键点，这部分依赖商汤的SDK（可以用开源库替代，我试过用Dlib，但效果没它好）。至于显示贴纸，”吐彩虹“、”眼睛冒火“那种是用GLSL实现的，3D模型那种是用Rajawali（OpenGL ES引擎）实现的。

**Comment by lin65505578** [comment]
3q
