### ISSUE TITLE
贴纸制作

### ISSUE THREAD

**Issue by ICECHN** [SimonCherryGZ/ARCamera#7]
你好，大神，请问这些贴纸哪里可以制作或者哪里有可能参考的？

**Comment by SimonCherryGZ** [comment]
你好，我只是初学者啊，以下是真正的大神的项目：
[AndroidOpenGLDemo](https://github.com/doggycoder/AndroidOpenGLDemo) by doggycoder
[Omoshiroi](https://github.com/Martin20150405/Omoshiroi) by Martin20150405
我这个项目也是参考了他们的。

关于贴纸，如果是类似吐彩虹那种，是用GLSL写的。
可以看下https://www.shadertoy.com 这个网站。
我这个吐彩虹效果其实也是借鉴上面的代码。

如果是3D模型那种，是利用了一个叫Rajawali的OpenGL ES引擎。
项目地址：https://github.com/Rajawali/Rajawali
它的DEMO非常丰富，我这个项目中的所有3D效果都可以在这个DEMO中找到。

下载3D模型可以看下这两个网站：
https://www.yobi3d.com
https://www.models-resource.com/

修改、制作简单的3D模型我推荐使用[Blender](https://www.blender.org/)，体积小，功能也很齐全。
