### ISSUE TITLE
License Terms

### ISSUE THREAD

**Issue by shubhwicked** [SimonCherryGZ/ARCamera#8]
hello,
  Is your project need some license agreement for commercial use, and how can i create more faces for it.
Also i are using stmobile for face land marking method, i think this sdk is paid.
Can you elaborate the whole process for this.
 Thank you.

**Comment by SimonCherryGZ** [comment]
> Is your project need some license agreement for commercial use

This project base on the following  projects:
https://github.com/doggycoder/AndroidOpenGLDemo
https://github.com/Martin20150405/Omoshiroi using MIT License
https://github.com/Rajawali/Rajawali using Apache License

I am not clear about software license, you should check their project.
3D model also has license. If you want to use them, you should refer to [README.md](https://github.com/SimonCherryGZ/ARCamera/blob/master/README.md) for information.

> and how can i create more faces for it.

I use this [picture](https://github.com/SimonCherryGZ/ARCamera/blob/master/app/src/main/res/drawable-nodpi/base_texture.jpg) to create face model (2 landmarks connected into 1 line, 3 lines connected into 1 face...), and use this picture as texture. So if you want to create another face, use this picture as reference,  then use Image processing software(such as Photoshop) to create another texture. In this project, the ["lion face"](https://github.com/SimonCherryGZ/ARCamera/blob/master/app/src/main/res/drawable-nodpi/lion_texture.jpg)、[“skull face”](https://github.com/SimonCherryGZ/ARCamera/blob/master/app/src/main/res/drawable-nodpi/skull_texture.png) is created by this method.

> Also i are using stmobile for face land marking method, i think this sdk is paid.
Can you elaborate the whole process for this.

The stmobile SDK i found it from [Omoshiroi](https://github.com/Martin20150405/Omoshiroi), and i have not plan to commercial use, so i don't know how to pay for the commercial edtion. Maybe you should check their official website: https://www.sensetime.com/
