### ISSUE TITLE
How to detect Wink

### ISSUE THREAD

**Issue by VineshChauhan24** [SimonCherryGZ/ARCamera#9]
i am using or libraray to detect face and learn how to work with face recognization system but i want to know that how i can dtect wink and which eye wink with id is it possible with your code?

**Comment by SimonCherryGZ** [comment]
I think you could detect it by calculate the distance between the upper and lower landmark of the eye.
Please refer to this [face landmark diagram](https://github.com/SimonCherryGZ/ARCamera/blob/master/app/src/main/res/drawable-nodpi/base_texture.jpg).
